### ISSUE TITLE
No database health check

### ISSUE THREAD

**Issue by karmek-k** [bootkemp-dev/datacat-backend#4]
Sometimes the backend loads earlier than the database, which leads to server panic and process termination. I think that the following may solve the problem:

1. [Performing a health check in the server's dockerfile](https://scoutapm.com/blog/how-to-use-docker-healthcheck)
2. I can see that [miniflux](https://miniflux.app/)'s `docker-compose.yml` file has these lines:

```yaml
version: '3'
services:
  miniflux:
    image: miniflux/miniflux:latest
    ports:
      - "80:8080"
    
    # THIS vvv

    depends_on:
      db:
        condition: service_healthy

    # THIS ^^^

    environment:
      - DATABASE_URL=postgres://miniflux:secret@db/miniflux?sslmode=disable
  db:
    image: postgres:latest
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
    volumes:
      - miniflux-db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
volumes:
  miniflux-db:
```

Maybe adding `condition: service_healthy` could solve the issue?

**Comment by karmek-k** [comment]
Ah, and there is the `healthcheck` section in `db` service:

```yaml
healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
```
